name: Build and Release AI Workspace

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'pipeline/**'
  pull_request:
    branches:
      - 'pipeline/**'
  workflow_dispatch:
    inputs:
      ui_version:
        description: 'UI version (tag) from wsp-desktop-ui (e.g., v1.0.0). Leave blank for latest artifact.'
        required: false
        type: string

permissions:
  contents: write
  issues: write

jobs:
  fetch-ui-artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.download.outputs.artifact_path }}
    steps:
      - name: Determine UI Artifact
        id: fetch_artifact
        run: |
          if [ -n "${{ github.event.inputs.ui_version }}" ]; then
            UI_TAG="${{ github.event.inputs.ui_version }}"
            ARTIFACT_NAME="wsp-desktop-ui-full-$UI_TAG"
            echo "Fetching specific artifact: $ARTIFACT_NAME"
            gh run list --repo officekube/wsp-desktop-ui --branch "$UI_TAG" --status completed --limit 10 --json databaseId,name,conclusion > runs.json
            echo "Raw gh run list output:"
            cat runs.json
            RUN_ID=$(jq -r '.[] | select(.name == "Build and Zip UI" and .conclusion == "success") | .databaseId' runs.json | head -n 1)
            if [ -z "$RUN_ID" ]; then
              echo "Error: No successful 'Build and Zip UI' run found for tag $UI_TAG in wsp-desktop-ui"
              exit 1
            fi
          else
            echo "No UI version specified. Fetching latest successful artifact."
            gh run list --repo officekube/wsp-desktop-ui --status completed --limit 10 --json databaseId,name,conclusion > runs.json
            echo "Raw gh run list output:"
            cat runs.json
            RUN_ID=$(jq -r '.[] | select(.name == "Build and Zip UI" and .conclusion == "success") | .databaseId' runs.json | head -n 1)
            if [ -z "$RUN_ID" ]; then
              echo "Error: No successful 'Build and Zip UI' runs found in wsp-desktop-ui"
              exit 1
            fi
            gh run view $RUN_ID --repo officekube/wsp-desktop-ui --json artifacts > artifacts.json
            echo "Raw artifacts output:"
            cat artifacts.json
            ARTIFACT_NAME=$(jq -r '.artifacts[] | select(.name | startswith("wsp-desktop-ui-full-")) | .name' artifacts.json | head -n 1)
            if [ -z "$ARTIFACT_NAME" ]; then
              echo "Error: No artifact named 'wsp-desktop-ui-full-*' found in run $RUN_ID"
              exit 1
            fi
          fi
          echo "Selected artifact: $ARTIFACT_NAME"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download UI Artifact
        id: download
        run: |
          echo "Downloading artifact: ${{ steps.fetch_artifact.outputs.artifact_name }}"
          mkdir -p downloaded-ui
          gh run download ${{ steps.fetch_artifact.outputs.run_id }} --repo officekube/wsp-desktop-ui --name "${{ steps.fetch_artifact.outputs.artifact_name }}" -D downloaded-ui
          echo "Contents of downloaded-ui directory:"
          find downloaded-ui -type f | xargs ls -la
          EXPECTED_PATH="$(pwd)/downloaded-ui/${{ steps.fetch_artifact.outputs.artifact_name }}/wsp-desktop-ui-full.zip"
          if [ -f "$EXPECTED_PATH" ]; then
            echo "Found expected zip file at: $EXPECTED_PATH"
            echo "artifact_path=$EXPECTED_PATH" >> $GITHUB_OUTPUT
          else
            echo "Expected file not found at: $EXPECTED_PATH"
            ZIP_FILE=$(find downloaded-ui -name "*.zip" | head -n 1)
            if [ -n "$ZIP_FILE" ]; then
              echo "Found zip file at: $ZIP_FILE"
              echo "artifact_path=$ZIP_FILE" >> $GITHUB_OUTPUT
            else
              echo "No zip files found in the downloaded artifact"
              exit 1
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload UI Artifact for Build
        uses: actions/upload-artifact@v4
        with:
          name: ui-full-files
          path: ${{ steps.download.outputs.artifact_path }}
          retention-days: 1

  build:
    needs: fetch-ui-artifact
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Match A’s Node version

      - name: Download runtimes
        run: npm run download-runtimes

      - name: Download UI Full Artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-full-files
          path: ./ui-files

      - name: Extract UI Artifact
        run: |
          echo "Contents of ui-files directory:"
          ls -la ui-files
          unzip -o ui-files/wsp-desktop-ui-full.zip -d .
          mv artifact/* .  # Move A’s files to root
          rm -rf artifact ui-files
          echo "Extracted contents:"
          ls -la
        working-directory: .

      - name: Install Dependencies
        run: npm ci  # Use A’s package.json

      - name: Build macOS Intel Installer
        if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build-mac-x64  # Use A’s script

      - name: Build macOS ARM Installer
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build-mac-arm64  # Use A’s script

      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build-win-x64  # Use A’s script

      - name: Build Linux Installer
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release  # Use A’s script

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/*.dmg
            dist/*.pkg
            dist/*.exe
            dist/*.msi
            dist/*.deb
            dist/*.rpm
            dist/*.AppImage
            dist/*.appimage
          retention-days: 5

  update-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts
          merge-multiple: false

      - name: Consolidate Artifacts
        shell: bash
        run: |
          mkdir -p release-assets
          for platform_dir in downloaded-artifacts/*; do
            if [ -d "$platform_dir" ]; then
              platform=$(basename "$platform_dir")
              case "$platform" in
                *"windows"*)
                  find "$platform_dir" -type f \( -name "*.exe" -o -name "*.msi" \) -exec cp -v {} release-assets/ \;
                  ;;
                *"macos"*)
                  find "$platform_dir" -type f \( -name "*.dmg" -o -name "*.pkg" \) -exec cp -v {} release-assets/ \;
                  ;;
                *"ubuntu"* | *"linux"*)
                  find "$platform_dir" -type f \( -name "*.deb" -o -name "*.rpm" -o -name "*.AppImage" -o -name "*.appimage" \) -exec cp -v {} release-assets/ \;
                  ;;
              esac
            fi
          done
          ls -la release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.fetch-ui-artifact.outputs.artifact_name }}  # Use A’s artifact tag
          files: release-assets/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Notes
        run: |
          npm install @octokit/rest
          RELEASE_TAG=${{ needs.fetch-ui-artifact.outputs.artifact_name }} node scripts/update-release.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}